# Dependencies
markdown:            kramdown
highlighter:         rouge

# Gems (for Jekyll 3.0)
gems: [jekyll-paginate]

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Colourstar
tagline:             'Game Coder,dream to reach all over the world'
description:         'Game Coder,product:Dream of ThreeAncientKindoms,Dream of TowerDefense,Dream of Rivakes.'
url:                 https://colourstar.github.io/
baseurl:             /
paginate:            7

# About/contact
author:
  name:              colourstar
  url:               https://twitter.com/colourstar
  email:             colourstar27@qq.com

# Custom vars
version:             2.0

# Social Media
github:				http://github.com/colourstar
twitter:			http://twitter.com/colourstar
disqus:             colourstar

# Theme Author (Please don't edit this line cause of MIT LICENSE rules)
theme:
  creator:			colourstar
  codename:			colourstar
  link:             https://github.com/colourstar
